import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import MainSection1 from "./components/MainSection1";
import {Sansita} from "next/font/google";

export const metadata = {
  title: "ZealTaste",
  description: "Generated by create next app",
};

const sansita = Sansita({
  subsets: ["latin"],
  weight: ['400', '700'],
  variable: "--font-sansita",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{background:'#f9efe6'}} className={`${sansita.variable} font-sansita px-6 md:px-40 py-1`}>
          <Header/>
          <MainSection1/>
        {children}
      </body>
    </html>
  );
};
